Repository kubernetes/git-sync, pull requests merged in 2019-10, with the labels that each got.

#185 :sparkles: add submodules support
  cmd/git-sync/main.go
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#187 support --depth flag for submodules
  cmd/git-sync/main.go
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#190 Replace exec.Command with runCommand
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#197 Fix minor issues from linters
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#194 Handle running as PID 1
  Dockerfile.in
  cmd/git-sync/main.go
  pkg/pid1/pid1.go
Labels: approved, cncf-cla: yes, lgtm, size/M
