Repository kubernetes/git-sync, pull requests merged in 2019-01, with the labels that each got.

#124 fix e2e script to work with os/arch tags
  test_e2e.sh
Labels: cncf-cla: yes

#123 Add a configurable timeout to the sync process
  cmd/git-sync/main.go
  slow_git.sh
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#133 Add option to allow for unlimited failures
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#132 Add flags/env-vars for additional SSH options
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#138 Use depth option when doing fetches
  cmd/git-sync/main.go
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#122 Allow to build container behind a proxy
  Makefile
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#139 e2e test for #135 and #131
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#140 Clean up / document build and release
  Makefile
  RELEASING.md
  build/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#141 Build rel tweaks
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#142 ~ -> $HOME
  docs/ssh.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
