Repository kubernetes/git-sync, pull requests merged in 2020-10, with the labels that each got.

#285 add an option to run the command when the repository is updated
  README.md
  cmd/git-sync/main.go
  test_e2e.sh
  test_sync_hook_command.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#292 Move --v into e2e framework (always same value)
  test_e2e.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#293 Fix line breaks in README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#294 docs: add PAT option for `--password`
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#295 README: add buildx comment
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
