Repository kubernetes/git-sync, pull requests merged in 2020-01, with the labels that each got.

#218 Support ssh as arbitrary users, add e2e for SSH
  Dockerfile.in
  Makefile
  _test_tools/sshd/Dockerfile
  _test_tools/sshd/README.md
  _test_tools/sshd/sshd.sh
  _test_tools/sshd/sshd_config
  cmd/git-sync/main.go
  docs/ssh.md
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#223 Update deployment to use new version which is multi-arch
  demo/config/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#224 Make health check meaningful
  cmd/git-sync/main.go
  slow_git.sh
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#230 Bump to debian-base 2.0.0 (buster)
  Makefile
  cmd/git-sync/main.go
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
