Repository kubernetes/git-sync, pull requests merged in 2020-11, with the labels that each got.

#298 Add help and manual flags, use pflag
  README.md
  cmd/git-sync/main.go
  go.mod
  go.sum
  test_e2e.sh
  vendor/github.com/spf13/pflag/.gitignore
  vendor/github.com/spf13/pflag/.travis.yml
  vendor/github.com/spf13/pflag/LICENSE
  vendor/github.com/spf13/pflag/README.md
  vendor/github.com/spf13/pflag/bool.go
  vendor/github.com/spf13/pflag/bool_slice.go
  vendor/github.com/spf13/pflag/bytes.go
  vendor/github.com/spf13/pflag/count.go
  vendor/github.com/spf13/pflag/duration.go
  vendor/github.com/spf13/pflag/duration_slice.go
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/float32.go
  vendor/github.com/spf13/pflag/float32_slice.go
  vendor/github.com/spf13/pflag/float64.go
  vendor/github.com/spf13/pflag/float64_slice.go
  vendor/github.com/spf13/pflag/go.mod
  vendor/github.com/spf13/pflag/go.sum
  vendor/github.com/spf13/pflag/golangflag.go
  vendor/github.com/spf13/pflag/int.go
  vendor/github.com/spf13/pflag/int16.go
  vendor/github.com/spf13/pflag/int32.go
  vendor/github.com/spf13/pflag/int32_slice.go
  vendor/github.com/spf13/pflag/int64.go
  vendor/github.com/spf13/pflag/int64_slice.go
  vendor/github.com/spf13/pflag/int8.go
  vendor/github.com/spf13/pflag/int_slice.go
  vendor/github.com/spf13/pflag/ip.go
  vendor/github.com/spf13/pflag/ip_slice.go
  vendor/github.com/spf13/pflag/ipmask.go
  vendor/github.com/spf13/pflag/ipnet.go
  vendor/github.com/spf13/pflag/string.go
  vendor/github.com/spf13/pflag/string_array.go
  vendor/github.com/spf13/pflag/string_slice.go
  vendor/github.com/spf13/pflag/string_to_int.go
  vendor/github.com/spf13/pflag/string_to_int64.go
  vendor/github.com/spf13/pflag/string_to_string.go
  vendor/github.com/spf13/pflag/uint.go
  vendor/github.com/spf13/pflag/uint16.go
  vendor/github.com/spf13/pflag/uint32.go
  vendor/github.com/spf13/pflag/uint64.go
  vendor/github.com/spf13/pflag/uint8.go
  vendor/github.com/spf13/pflag/uint_slice.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#299 Change time-related flags to durations
  README.md
  cmd/git-sync/main.go
  cmd/git-sync/webhook.go
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#301 Add tests for other env funcs
  cmd/git-sync/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#300 Change some flags (breaking)
  README.md
  cmd/git-sync/main.go
  demo/config/deployment.yaml
  docs/ssh.md
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#305 Add a test for tabs in manual
  cmd/git-sync/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#302 Normalize the root path
  cmd/git-sync/main.go
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#303 Clarify logging vs printf for fatal messages
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#304 Add a "main struct" with methods
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#307 Add the `--root` flag into the Usage section
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
