Repository kubernetes/git-sync, pull requests merged in 2020-09, with the labels that each got.

#269 Trivial comment change
  cmd/git-sync/main.go
Labels: size/XS

#270 Remove useless test case
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#271 Minor tweaks to submodules strings & consts
  README.md
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#272 Move setFlagDefaults closer to flag code
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#274 Improve logs when running a command
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#276 use filepath.Join, drop dep on path
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#277 Better logs and errors
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#273 Improve flag input checking and errors
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#275 Add metric for askpass, noop sync != success
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#278 Clean up askpass function to take url as arg
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#280 add socat to image to allow for proxying. Fixes #279
  Dockerfile.in
  docs/proxy.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#282 Use new staging GCR
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#243 Relax wait between sync
  README.md
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, lifecycle/frozen, ok-to-test, size/XS

#289 Fix webhook regression: allow -1 to ignore status
  cmd/git-sync/main.go
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#291 logtostderr defaults to true: don't set it in test
  test_e2e.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S
