Repository kubernetes/git-sync, pull requests merged in 2021-07, with the labels that each got.

#432 Update to latest base image debian-base:buster-v1.8.0
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#433 Bump base image version (v4 branch)
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#434 Remove broken analytics links
  README.md
  demo/README.md
  demo/blog/content/about.md
  demo/blog/content/post/first.md
  demo/hugo/README.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#431 Add option to read password from file
  README.md
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#436 Small nits I found with password-file while porting #431
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#435 Add option to read passwd from file (v3 branch)
  README.md
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M
