Repository kubernetes/git-sync, pull requests merged in 2021-03, with the labels that each got.

#346 Update git from backports
  Dockerfile.in
Labels: approved, cncf-cla: yes, lgtm, size/S

#347 Update git from backports
  Dockerfile.in
Labels: approved, cncf-cla: yes, lgtm, size/S

#348 Build container without cache
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#349 Build container without cache
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#341 Add --git-config flag
  README.md
  cmd/git-sync/main.go
  cmd/git-sync/main_test.go
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#353 Fix tests on master - reset needs "--" arg
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#342 Add --git-config flag
  README.md
  cmd/git-sync/main.go
  cmd/git-sync/main_test.go
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#343 Fix exit non-zero exit codes when running as pid1
  cmd/git-sync/main.go
  pkg/pid1/pid1.go
  pkg/pid1/test/fast-exit/main.go
  pkg/pid1/test/fast-exit/test.sh
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#344 Fix exit non-zero exit codes when running as pid1
  cmd/git-sync/main.go
  pkg/pid1/pid1.go
  pkg/pid1/test/fast-exit/main.go
  pkg/pid1/test/fast-exit/test.sh
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#360 Don't require a TTY to build/test
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#362 Don't require a TTY to build/test
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#354 Add GIT_SYNC_ROOT change for non-root user in docs/ssh
  docs/ssh.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, tide/merge-method-squash
