Repository kubernetes/git-sync, pull requests merged in 2021-06, with the labels that each got.

#402 Update README to spec UID/GID
  README.md
Labels: approved, cncf-cla: yes, size/S

#403 Update README to spec UID/GID
  README.md
Labels: approved, cncf-cla: yes, size/S

#407 Improve error message for askpass.
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#408 Improve error message for askpass.
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#405 bump to logr v1.0.0-rc1
  go.mod
  go.sum
  vendor/github.com/go-logr/glogr/README.md
  vendor/github.com/go-logr/glogr/glogr.go
  vendor/github.com/go-logr/glogr/go.mod
  vendor/github.com/go-logr/glogr/go.sum
  vendor/github.com/go-logr/logr/CHANGELOG.md
  vendor/github.com/go-logr/logr/CONTRIBUTING.md
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/discard.go
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#406 bump to logr v1.0.0-rc1 (v4)
  go.mod
  go.sum
  vendor/github.com/go-logr/glogr/README.md
  vendor/github.com/go-logr/glogr/glogr.go
  vendor/github.com/go-logr/glogr/go.mod
  vendor/github.com/go-logr/glogr/go.sum
  vendor/github.com/go-logr/logr/CHANGELOG.md
  vendor/github.com/go-logr/logr/CONTRIBUTING.md
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/discard.go
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#416 unbreak e2e for github (v4)
  test_e2e.sh
Labels: approved, cncf-cla: yes, size/XS

#414 Cleanup worktree defensively
  cmd/git-sync/main.go
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#418 Clean up worktree dirs during sync loop
  cmd/git-sync/main.go
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#413 Check for rev to be present after a fetch
  cmd/git-sync/main.go
  slow_git_clone.sh
  slow_git_fetch.sh
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#421 Handle a race between ls-remote and fetch
  cmd/git-sync/main.go
  slow_git_clone.sh
  slow_git_fetch.sh
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#419 Add Janet and Nan as approvers (3.x)
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#420 Add Janet and Nan as approvers (master)
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#426 Update RELEASING doc
  RELEASING.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#427 Update RELEASING doc (v4 branch)
  RELEASING.md
Labels: approved, cncf-cla: yes, lgtm, size/M
