Repository kubernetes/git-sync, pull requests merged in 2021-11, with the labels that each got.

#451 v4: use repo default branch instead of master
  README.md
  cmd/git-sync/main.go
  test_e2e.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#454 fix typo
  README.md
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#455 v4: Replace glogr with funcr
  cmd/git-sync/main.go
  go.mod
  go.sum
  pkg/logging/logging.go
  vendor/github.com/go-logr/glogr/LICENSE
  vendor/github.com/go-logr/glogr/README.md
  vendor/github.com/go-logr/glogr/glogr.go
  vendor/github.com/go-logr/glogr/go.mod
  vendor/github.com/go-logr/glogr/go.sum
  vendor/github.com/go-logr/logr/.golangci.yaml
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/funcr/funcr.go
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/modules.txt
Labels: cncf-cla: yes, approved, lgtm, size/XXL
