Repository kubernetes/git-sync, pull requests merged in 2021-04, with the labels that each got.

#370 Move sync-hook to after symlink flip
  .gitallowed
  cmd/git-sync/main.go
  test_e2e.sh
  test_sync_hook_command.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#371 Move sync-hook to after symlink flip
  .gitallowed
  cmd/git-sync/main.go
  test_e2e.sh
  test_sync_hook_command.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#331 Export the error details to an error file
  cmd/git-sync/main.go
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#376 Update to latest base image debian-base:buster-v1.6.0
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#377 Update to latest base image debian-base:buster-v1.6.0 (v4)
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#378 Fix licenses for other arch'es
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#379 Fix licenses for other arch'es
  Makefile
Labels: cncf-cla: yes

#375 Export the error details to an error file
  README.md
  cmd/git-sync/main.go
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#372 Add support for sparse-checkout
  README.md
  cmd/git-sync/main.go
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#381 Add support for sparse-checkout (v4 vbranch)
  Makefile
  README.md
  cmd/git-sync/main.go
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L
