Repository kubernetes/git-sync, pull requests merged in 2021-05, with the labels that each got.

#383 Create the root directory if it doesn't exist
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#385 Create the root directory if it doesn't exist
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#386 Clean up global flRoot use (v4)
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#387 Clean up global flRoot use
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#392 move test cleanup to the end (v3)
  test_e2e.sh
Labels: approved, cncf-cla: yes, size/S

#391 move test cleanup to the end (v4)
  test_e2e.sh
Labels: approved, cncf-cla: yes, size/S

#389 Grant read access for the error file to all users
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#390 Grant read access for the error file to all users
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#393 Small error string cleanup (v3)
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, size/XS

#394 Small error string cleanup (v4)
  cmd/git-sync/main.go
Labels: approved, cncf-cla: yes, size/XS

#396 Make sure all code files have headers
  _test_tools/ncsvr/Dockerfile
  _test_tools/ncsvr/ncsvr.sh
  _test_tools/sshd/Dockerfile
  _test_tools/sshd/sshd.sh
  askpass_git.sh
  cmd/git-sync/webhook.go
  cmd/git-sync/webhook_test.go
  pkg/pid1/pid1.go
  pkg/pid1/test/fast-exit/Dockerfile
  pkg/pid1/test/fast-exit/main.go
  pkg/pid1/test/fast-exit/test.sh
  slow_git.sh
  test_e2e.sh
  test_sync_hook_command.sh
Labels: approved, cncf-cla: yes, size/L

#397 Make sure all code files have headers
  _test_tools/ncsvr/Dockerfile
  _test_tools/ncsvr/ncsvr.sh
  _test_tools/sshd/Dockerfile
  _test_tools/sshd/sshd.sh
  askpass_git.sh
  cmd/git-sync/webhook.go
  cmd/git-sync/webhook_test.go
  pkg/pid1/pid1.go
  pkg/pid1/test/fast-exit/Dockerfile
  pkg/pid1/test/fast-exit/main.go
  pkg/pid1/test/fast-exit/test.sh
  slow_git.sh
  test_e2e.sh
  test_sync_hook_command.sh
Labels: approved, cncf-cla: yes, size/L

#399 Downgrade libcurl to work around HTTP bug (v4)
  Dockerfile.in
  Makefile
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#398 Downgrade libcurl to work around HTTP bug (v3)
  Dockerfile.in
  Makefile
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#401 Change libcurl workaround to be less precise (v4)
  Dockerfile.in
Labels: approved, cncf-cla: yes, size/XS

#400 Change libcurl workaround to be less precise (v3)
  Dockerfile.in
Labels: approved, cncf-cla: yes, size/XS
