Repository kubernetes/git-sync, pull requests merged in 2022-06, with the labels that each got.

#526 Fix Makefile to run tools on host OS/ARCH (v4)
  Makefile
Labels: cncf-cla: yes, size/M, approved, lgtm

#528 Pass CLEANUP=0 to test_e2e to leave logs (v4 branch)
  test_e2e.sh
Labels: cncf-cla: yes, size/XS, approved

#529 Pass CLEANUP=0 to test_e2e to leave logs (v3)
  test_e2e.sh
Labels: cncf-cla: yes, size/XS, approved

#531 Make ssh e2e test not use --one-time
  test_e2e.sh
Labels: cncf-cla: yes, size/S, approved, lgtm

#530 Make ssh e2e test not use --one-time (v3)
  test_e2e.sh
Labels: cncf-cla: yes, size/S, approved, lgtm

#534 upgrade base image to address vulnerabilities
  Dockerfile.in
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm
