Repository kubernetes/git-sync, pull requests merged in 2022-03, with the labels that each got.

#495 Add GC controls, e2e regexes (v3 branch)
  cmd/git-sync/main.go
  test_e2e.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#496 Add GC controls, e2e regexes (v4 branch)
  cmd/git-sync/main.go
  test_e2e.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#500 Update README to latest (master)
  README.md
Labels: cncf-cla: yes, size/L, approved, lgtm

#501 Overhaul flags in README (v3)
  README.md
Labels: cncf-cla: yes, size/L, approved, lgtm

#499 Support repo change between invocations
  cmd/git-sync/main.go
  test_e2e.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#502 update the base image to fix vulnerabilities
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#503 update the base image to fix vulnerabilities (v4)
  Makefile
Labels: cncf-cla: yes, size/XS, approved

#504 Clean up recently added test case
  test_e2e.sh
Labels: cncf-cla: yes, size/M

#505 Support repo change between invocations (v4)
  cmd/git-sync/main.go
  test_e2e.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#510 TrimSpace exec's stdout/stderr for log (v3)
  pkg/cmd/cmd.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#511 Only build test-tools when needed (v3)
  Makefile
Labels: cncf-cla: yes, size/S, approved, lgtm

#513 Only build test-tools when needed (v4)
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#514 Use logger.WithName() for web/exechook (v4)
  cmd/git-sync/main.go
  pkg/cmd/cmd.go
  pkg/hook/exechook.go
  pkg/hook/hook.go
  pkg/hook/webhook.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#509 update RELEASING (v3)
  RELEASING.md
Labels: cncf-cla: yes, size/M, approved, lgtm

#512 Update RELEASING (v4)
  RELEASING.md
Labels: cncf-cla: yes, size/M, approved, lgtm
