Repository kubernetes/git-sync, pull requests merged in 2022-07, with the labels that each got.

#537 v4: Fix inconsistency with build dotfile names
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#545 v3: Fix inconsistency with build dotfile names
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#539 v4: e2e: Reformat ncsvr scripts for readability
  test_e2e.sh
Labels: cncf-cla: yes, size/S, approved, lgtm

#547 v3: e2e: Reformat ncsvr scripts for readability
  test_e2e.sh
Labels: cncf-cla: yes, size/S, approved, lgtm

#540 v4: Clean up fail-count logging
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#548 v3: Clean up fail-count logging
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#542 v4: Split password test to 2 - right and wrong passwd
  test_e2e.sh
Labels: cncf-cla: yes, size/S, approved, lgtm

#550 v3: Split password test to 2 - right and wrong passwd
  test_e2e.sh
Labels: cncf-cla: yes, size/S, approved, lgtm

#552 v3: Add -q to apt-get commands
  Dockerfile.in
Labels: cncf-cla: yes, size/S, approved, lgtm

#544 v4: Add -q to apt-get commands
  Dockerfile.in
Labels: cncf-cla: yes, size/XS, approved, lgtm

#546 v3: e2e: Don't manually "docker kill"
  test_e2e.sh
Labels: cncf-cla: yes, size/S, approved, lgtm

#538 v4: e2e: Don't manually "docker kill"
  test_e2e.sh
Labels: cncf-cla: yes, size/S, approved, lgtm

#558 upgrade base image to address vulnerabilities
  Dockerfile.in
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#560 v4: Bump build image to go 1.18
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#559 v3: Bump build image to go 1.18
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#562 v4: Bump go.mod to 1.18
  go.mod
Labels: cncf-cla: yes, size/XS, approved, lgtm

#561 v3: Bump go.mod to 1.18
  go.mod
Labels: cncf-cla: yes, size/XS, approved, lgtm

#556 v3: e2e with -v=6
  test_e2e.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#557 v4: e2e with -v=6
  test_e2e.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#541 V4: beef up askpass-url test
  askpass_git.sh
  test_e2e.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#549 V3: beef up askpass-url test
  askpass_git.sh
  cmd/git-sync/main.go
  test_e2e.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#543 V4: Rename e2e tests for easier partial runs
  test_e2e.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#551 V3: Rename e2e tests for easier partial runs
  test_e2e.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#563 v3: e2e: rebuild the container less often
  Dockerfile.in
  Makefile
  test_e2e.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#564 v4: e2e: rebuild the container less often
  Dockerfile.in
  Makefile
  test_e2e.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#565 v3: Bring some Makefile cleanups from k/k
  Makefile
Labels: cncf-cla: yes, size/L, approved, lgtm

#589 Fix CVE-2022-2068
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#590 Fix CVE-2022-2068
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#567 v3: e2e: Fix ncsvr to wait for input on HTTP
  _test_tools/ncsvr/ncsvr.sh
  test_e2e.sh
Labels: cncf-cla: yes, size/M, approved

#568 v4: e2e: Fix ncsvr to wait for input on HTTP
  _test_tools/ncsvr/ncsvr.sh
  test_e2e.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#569 v3: e2e: $CLEANUP decides whether to rm containers
  test_e2e.sh
Labels: cncf-cla: yes, size/S, approved, lgtm

#572 v4: Clean up askpass_URL
  askpass_git.sh
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#574 v4: e2e: don't set XDG_CONFIG_HOME
  test_e2e.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#575 v3: e2e: Make password test not use --one-time
  test_e2e.sh
Labels: cncf-cla: yes, size/S, approved, lgtm

#578 v4: Clean up credential init
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#579 v3: Logging and error handling cleanup
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#580 v4: Logging and error handling cleanup
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#581 v3: log.V(9) md5sums of credentials
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#582 v4: log.V(9) md5sums of credentials
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#583 v3: Change from "store" to "cache" for credentials
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#584 v4: Change from "store" to "cache" for credentials
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#585 v3: Don't set known_hosts to /dev/null
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#586 v4: Don't set known_hosts to /dev/null
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#594 Fix wrong env var name in docs
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#595 e2e: also trap ERR
  test_e2e.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#596 Log a redacted form of environment at startup
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/M, approved, lgtm
