Repository kubernetes/git-sync, pull requests merged in 2022-01, with the labels that each got.

#462 Avoid writing to /etc/passwd unless needed
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#465 Expose the ssh diagnostic message
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#466 fix: resolve issue #463
  cmd/git-sync/main.go
  pkg/hook/hook.go
  test_e2e.sh
  test_exechook_command_fail_with_sleep.sh
  test_exechook_command_with_sleep.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#469 Ensure web/exec hooks complete in --one-time
  cmd/git-sync/main.go
  pkg/hook/hook.go
  test_e2e.sh
  test_exechook_command_fail_with_sleep.sh
  test_exechook_command_with_sleep.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#468 Followup to #466 - small cleanups for one-time hooks
  cmd/git-sync/main.go
  pkg/hook/hook.go
  test_e2e.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#471 Fix e2e, dropped 'finish()' func
  test_e2e.sh
Labels: cncf-cla: yes, size/S, approved

#473 Don't try to remove the root if it appears corrupt (v3)
  cmd/git-sync/main.go
  test_e2e.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#472 Don't try to remove the root if it appears corrupt (v4)
  cmd/git-sync/main.go
  test_e2e.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#475 Don't double-register the hook metric (v3)
  pkg/hook/hook.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#476 Don't double-register the hook metric (v4)
  pkg/hook/hook.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#477 Allow --dest to be an absolute path (v3)
  cmd/git-sync/main.go
  test_e2e.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#478 Allow --dest to be an absolute path (v4)
  cmd/git-sync/main.go
  test_e2e.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#479 Fix bug caused in previous PR (v3)
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/XS, approved

#480 Fix bug caused in previous PR (v4)
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/S

#483 Bump to go 1.17
  Makefile
  go.mod
  vendor/github.com/go-logr/glogr/go.mod
  vendor/github.com/go-logr/glogr/go.sum
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/google/go-licenses/go.mod
  vendor/github.com/google/go-licenses/go.sum
  vendor/github.com/google/licenseclassifier/go.mod
  vendor/github.com/google/licenseclassifier/go.sum
  vendor/github.com/mitchellh/go-homedir/go.mod
  vendor/github.com/otiai10/copy/go.mod
  vendor/github.com/otiai10/copy/go.sum
  vendor/github.com/prometheus/procfs/go.mod
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/pflag/go.mod
  vendor/github.com/spf13/pflag/go.sum
  vendor/github.com/xanzy/ssh-agent/go.mod
  vendor/github.com/xanzy/ssh-agent/go.sum
  vendor/gopkg.in/src-d/go-billy.v4/go.mod
  vendor/gopkg.in/src-d/go-billy.v4/go.sum
  vendor/gopkg.in/src-d/go-git.v4/go.mod
  vendor/gopkg.in/src-d/go-git.v4/go.sum
  vendor/modules.txt
Labels: cncf-cla: yes, size/L, approved, lgtm
