Repository kubernetes/git-sync, pull requests merged in 2022-11, with the labels that each got.

#640 refactor: move from io/ioutil to io and os packages
  cmd/git-sync/main.go
  cmd/git-sync/main_test.go
  pkg/logging/logging.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#642 V3: Allow quoted keys for --git-config
  cmd/git-sync/main.go
  cmd/git-sync/main_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#643 V4: Allow quoted keys for --git-config
  cmd/git-sync/main.go
  cmd/git-sync/main_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#648 V3 e2e: fix git submodules for file://
  test_e2e.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#647 V4 e2e: fix git submodules for file://
  test_e2e.sh
Labels: cncf-cla: yes, size/S, approved, lgtm

#649 e2e: fix 2 broken tests
  cmd/git-sync/main.go
  test_e2e.sh
Labels: cncf-cla: yes, size/M, approved, lgtm
