Repository kubernetes/git-sync, pull requests merged in 2023-07, with the labels that each got.

#765 Make relative-path submodules work, via origin
  main.go
  pkg/cmd/cmd.go
  test_e2e.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#766 Document the / URL of the HTTP port
  README.md
  main.go
Labels: cncf-cla: yes, size/S, approved

#771 Update README.md
  README.md
Labels: cncf-cla: yes, approved

#772 Update README.md
  README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#778 Handle errors from credential refresh
  main.go
  test_e2e.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#782 Handle errors from credential refresh (v3)
  cmd/git-sync/main.go
  test_e2e.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#781 Drop distroless and DIY
  Dockerfile.in
  clean_distroless.sh
  stage_binaries.sh
  test_e2e.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#784 Remove trailing newlines from errors
  main.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#783 Lint fixes (part 1)
  main.go
  main_test.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#786 Enable github actions for CI
  .github/workflows/main.yml
  test_e2e.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#790 Add dependabot for github actions
  .github/dependabot.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#789 Replace all error %v with %w
  main.go
  pkg/pid1/pid1.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#791 Rename github build workflow
  .github/workflows/main.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#788 Fix goroutine leak in git option parsing
  go.mod
  go.sum
  main.go
  main_test.go
  vendor/go.uber.org/goleak/.gitignore
  vendor/go.uber.org/goleak/CHANGELOG.md
  vendor/go.uber.org/goleak/LICENSE
  vendor/go.uber.org/goleak/Makefile
  vendor/go.uber.org/goleak/README.md
  vendor/go.uber.org/goleak/doc.go
  vendor/go.uber.org/goleak/glide.yaml
  vendor/go.uber.org/goleak/internal/stack/doc.go
  vendor/go.uber.org/goleak/internal/stack/stacks.go
  vendor/go.uber.org/goleak/leaks.go
  vendor/go.uber.org/goleak/options.go
  vendor/go.uber.org/goleak/testmain.go
  vendor/go.uber.org/goleak/tracestack_new.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/XL, approved, lgtm

#792 lint: fix remaining lint issues.
  main.go
  pkg/pid1/pid1.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#794 Add /tmp to staging
  Dockerfile.in
Labels: cncf-cla: yes, size/XS, approved, lgtm
