Repository kubernetes/git-sync, pull requests merged in 2023-05, with the labels that each got.

#722 Make all env var names GITSYNC_FOO
  Dockerfile.in
  README.md
  cmd/git-sync/main.go
  cmd/git-sync/main_test.go
  demo/config/deployment.yaml
  docs/askpass-url.md
  docs/cookie-file.md
  docs/ssh.md
  test_e2e.sh
  v3-to-v4.md
Labels: cncf-cla: yes, size/L, approved

#727 Make flag defs easier to read
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/L, approved

#725 Capture and simplify a git.Run() method
  cmd/git-sync/main.go
  pkg/cmd/cmd.go
  pkg/hook/exechook.go
Labels: cncf-cla: yes, size/M, approved

#726 Update to golang 1.19 for vulnerability fixes
  Makefile
  go.mod
Labels: cncf-cla: yes, size/XS, approved, lgtm

#732 Update to go 1.20
  Makefile
  go.mod
Labels: cncf-cla: yes, size/XS, approved, lgtm

#730 Update to go 1.20
  Makefile
  go.mod
Labels: cncf-cla: yes, size/XS, approved, lgtm

#729 Fetch just once per run and when hash changes
  cmd/git-sync/main.go
  test_e2e.sh
Labels: cncf-cla: yes, size/L, approved

#733 Prevent git's 'dubious ownership' error (on v4 branch)
  cmd/git-sync/main.go
  pkg/logging/logging.go
  test_e2e.sh
Labels: cncf-cla: yes, size/M, approved

#734 Rename metric variables
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/S, approved

#735 Support in-place updates from v3
  cmd/git-sync/main.go
  test_e2e.sh
  v3-to-v4.md
Labels: cncf-cla: yes, size/M, approved

#736 Reorganize and rename deprecated flags vars
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/M, approved

#737 e2e: Fix weirdly quoted strings
  test_e2e.sh
Labels: cncf-cla: yes, size/XL, approved

#738 EOL the `--change-permissions` flag
  cmd/git-sync/main.go
  v3-to-v4.md
Labels: cncf-cla: yes, size/M, approved

#715 Add --stale-worktree-timeout option
  cmd/git-sync/main.go
  test_e2e.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#740 Reorganize flag definitions
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/S, approved

#741 Get rid of "must not start with ." logic
  README.md
  cmd/git-sync/main.go
  test_e2e.sh
Labels: cncf-cla: yes, size/M, approved

#742 Add a unit test for touch()
  cmd/git-sync/main_test.go
Labels: cncf-cla: yes, size/M, approved

#743 Tighten up cleanup to be called once per loop
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/M, approved

#744 Update README and other docs
  README.md
  cmd/git-sync/main.go
  docs/askpass-url.md
  docs/cookie-file.md
  docs/proxy.md
  v3-to-v4.md
Labels: cncf-cla: yes, size/L, approved

#745 Move flag defs into main()
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/L, approved

#746 Move main.go to root of repo
  main.go
  main_test.go
Labels: cncf-cla: yes, size/XS, approved

#747 Log actual flags rather than args+env
  main.go
Labels: cncf-cla: yes, size/M, approved

#749 Improve logging levels a bit
  main.go
Labels: cncf-cla: yes, size/M, approved

#751 Run hooks at startup
  README.md
  _test_tools/exechook_command.sh
  main.go
  test_e2e.sh
  v3-to-v4.md
Labels: cncf-cla: yes, size/L, approved
