Repository kubernetes/git-sync, pull requests merged in 2023-02, with the labels that each got.

#667 Fix e2e on 3.x
  test_e2e.sh
Labels: cncf-cla: yes, size/S, approved, lgtm

#670 Fix e2e on v4
  test_e2e.sh
Labels: cncf-cla: yes, size/S, approved, lgtm

#671 v3: Log commands we run with original caller
  pkg/cmd/cmd.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#675 Log commands we run with original caller
  pkg/cmd/cmd.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#674 Require --http-bind when using other http flags
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#677 v4: Default http-metrics to false
  cmd/git-sync/main.go
Labels: cncf-cla: yes, approved

#676 v4: Deref tags on ls-remote
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#672 v3: Fix cases of syncing different SHAs back to back
  cmd/git-sync/main.go
  test_e2e.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#673 v4: e2e improvements
  test_e2e.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#664 Allow sync wait period to be truncated by an HUP signal.
  cmd/git-sync/main.go
  test_e2e.sh
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#678 Replace deprecated k8s registry references
  Makefile
  RELEASING.md
  demo/config/deployment.yaml
  docs/kubernetes.md
  docs/ssh.md
Labels: cncf-cla: yes, size/S, approved, lgtm

#679 e2e: move helper scripts to _test_tools/
  Makefile
  _test_tools/exechook_command.sh
  _test_tools/exechook_command_fail.sh
  _test_tools/exechook_command_fail_with_sleep.sh
  _test_tools/exechook_command_with_sleep.sh
  _test_tools/git_askpass.sh
  _test_tools/git_slow_clone.sh
  _test_tools/git_slow_fetch.sh
  test_e2e.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#681 Add logs when we use deprecated flags
  cmd/git-sync/main.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#682 e2e: rename init tests, remove default-val args
  test_e2e.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#680 Add a test to exercise git
  test_git.sh
Labels: cncf-cla: yes, size/XL, approved, lgtm

#683 fix typo
  pkg/cmd/cmd.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#684 Bump debian-base build image to v1.4.3
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm
