Repository kubernetes/git-sync, pull requests merged in 2023-10, with the labels that each got.

#809 Document V4 regression on --change-permissions
  v3-to-v4.md
Labels: cncf-cla: yes, size/S, do-not-merge/hold, approved

#803 Add --credential flag for multiple username/password
  README.md
  main.go
  test_e2e.sh
Labels: cncf-cla: yes, size/L, approved

#829 Update v3-v4 doc on ssh
  v3-to-v4.md
Labels: cncf-cla: yes, size/XS, approved

#830 Fix errors when parsing --repo for logging
  main.go
Labels: cncf-cla: yes, size/XS, approved

#828 fix: infinite bad loop caused by unexpected worktree directory removal
  main.go
  test_e2e.sh
Labels: cncf-cla: yes, size/M

#831 Break up main.go
  abspath.go
  abspath_test.go
  credential.go
  env.go
  env_test.go
  main.go
  main_test.go
Labels: cncf-cla: yes, approved, size/XXL

#835 Logging: log syncCount and be less scary
  main.go
Labels: cncf-cla: yes, size/S, approved

#834 Add e2e case for missing worktree after crash
  main.go
  test_e2e.sh
Labels: cncf-cla: yes, size/M, approved

#833 Remove errant use of --period with --one-time
  test_e2e.sh
Labels: cncf-cla: yes, size/XS, approved
