Repository kubernetes/git-sync, pull requests merged in 2024-06, with the labels that each got.

#882 Support -? as an alias for --help
  main.go
Labels: cncf-cla: yes, size/S, approved

#884 Bump go to 1.22
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XS, approved

#887 Log cleanups
  main.go
Labels: cncf-cla: yes, approved

#888 Add curl to the image
  Dockerfile.in
Labels: cncf-cla: yes, size/XS, approved

#883 Clean up flag-related messages
  env.go
  main.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#889 Retool the demo
  demo/README.md
  demo/blog/archetypes/.keep
  demo/blog/config.toml
  demo/blog/content/about.md
  demo/blog/content/post/first.md
  demo/blog/layouts/.keep
  demo/blog/static/.keep
  demo/config/deployment.yaml
  demo/deployment.yaml
  demo/html/index.html
  demo/hugo/Dockerfile
  demo/hugo/README.md
  demo/hugo/run-hugo
  demo/service.yaml
Labels: cncf-cla: yes, size/L, approved

#890 Fix new github actions e2e failure
  test_e2e.sh
Labels: cncf-cla: yes, size/M, approved

#892 test_e2e.sh: quote variables to prevent globbing and word splitting
  test_e2e.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#893 Remove e2e debug code
  test_e2e.sh
Labels: cncf-cla: yes, size/XS, approved

#894 consistently use bash shebang for shell scripts
  build/build.sh
  build/test.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#896 Revert 894, fix build scripts to be strict sh
  build/build.sh
  build/test.sh
Labels: cncf-cla: yes, size/S, approved, lgtm

#897 Fix default-value bug in build.sh
  build/build.sh
Labels: cncf-cla: yes, size/XS, approved

#900 use debian build image and bash build scripts
  Makefile
  build/build.sh
  build/test.sh
Labels: cncf-cla: yes, size/S, approved, lgtm

#901 test_e2e.sh: Use index to expand FUNCNAME
  test_e2e.sh
Labels: cncf-cla: yes, size/XL, approved, lgtm, ok-to-test

#899 Shellcheck stage_binaries.sh
  stage_binaries.sh
Labels: cncf-cla: yes, size/M, approved

#902 test_e2e.sh: shellcheck entire file
  test_e2e.sh
Labels: cncf-cla: yes, size/M

#904 Fix Slight Typos In Docs
  README.md
  v3-to-v4.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#905 test_git.sh: shellcheck entire file
  test_git.sh
Labels: cncf-cla: yes, size/M, approved, lgtm
